<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2022.2">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 13.0px Menlo; color: #1443ae; -webkit-text-stroke: #1443ae}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 13.0px Menlo; color: #18191b; -webkit-text-stroke: #18191b}
    p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 13.0px Menlo; color: #2e3133; -webkit-text-stroke: #2e3133; min-height: 15.0px}
    p.p4 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 13.0px Menlo; color: #2e3133; -webkit-text-stroke: #2e3133}
    p.p5 {margin: 0.0px 0.0px 0.0px 0.0px; line-height: 20.0px; font: 13.0px Menlo; color: #ba0673; -webkit-text-stroke: #ba0673}
    span.s1 {font-kerning: none; background-color: #fffffe}
    span.s2 {font-kerning: none; color: #2e3133; background-color: #fffffe; -webkit-text-stroke: 0px #2e3133}
    span.s3 {font-kerning: none; color: #18191b; background-color: #fffffe; -webkit-text-stroke: 0px #18191b}
    span.s4 {font-kerning: none; color: #1443ae; background-color: #fffffe; -webkit-text-stroke: 0px #1443ae}
    span.s5 {font-kerning: none; color: #ba0673; background-color: #fffffe; -webkit-text-stroke: 0px #ba0673}
    span.s6 {font-kerning: none; color: #a20010; background-color: #fffffe; -webkit-text-stroke: 0px #a20010}
    span.s7 {font-kerning: none}
    span.s8 {font-kerning: none; color: #12737e; background-color: #fffffe; -webkit-text-stroke: 0px #12737e}
  </style>
</head>
<body>
<p class="p1"><span class="s1">function</span><span class="s2"> </span><span class="s3">onStart</span><span class="s2">() {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">sheet</span><span class="s2"> = </span><span class="s5">SpreadsheetApp</span><span class="s2">.</span><span class="s1">getActiveSheet</span><span class="s2">();</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">range</span><span class="s2"> = </span><span class="s1">sheet</span><span class="s2">.</span><span class="s1">getRange</span><span class="s2">(</span><span class="s6">"c2:c10000"</span><span class="s2">);</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">to_replace_one</span><span class="s2"> = </span><span class="s6">" "</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">replace_with_one</span><span class="s2"> = </span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">to_replace_two</span><span class="s2"> = </span><span class="s6">"at"</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">replace_with_two</span><span class="s2"> = </span><span class="s6">"@"</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">to_replace_three</span><span class="s2"> = </span><span class="s6">" @ "</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">replace_with_three</span><span class="s2"> = </span><span class="s6">"@"</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">to_replace_four</span><span class="s2"> = </span><span class="s6">" dot "</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">replace_with_four</span><span class="s2"> = </span><span class="s6">"."</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s1">replaceInSheetOne</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">,</span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_one</span><span class="s2">, </span><span class="s1">replace_with_one</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s1">replaceInSheetTwo</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">, </span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_two</span><span class="s2">, </span><span class="s1">replace_with_two</span><span class="s2">)</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s1">replaceInSheetThree</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">, </span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_three</span><span class="s2">, </span><span class="s1">replace_with_three</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s1">replaceInSheetFour</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">, </span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_four</span><span class="s2">, </span><span class="s1">replace_with_four</span><span class="s2">);</span></p>
<p class="p4"><span class="s1">}</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s4">function</span><span class="s2"> </span><span class="s1">replaceInSheetOne</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">,</span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_one</span><span class="s2">, </span><span class="s1">replace_with_one</span><span class="s2">) {</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p5"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s3">ui</span><span class="s2"> = </span><span class="s1">SpreadsheetApp</span><span class="s2">.</span><span class="s3">getUi</span><span class="s2">();<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">spread</span><span class="s2"> = </span><span class="s5">SpreadsheetApp</span><span class="s2">.</span><span class="s1">getActiveSpreadsheet</span><span class="s2">();</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">data</span><span class="s2"><span class="Apple-converted-space">  </span>= </span><span class="s1">range</span><span class="s2">.</span><span class="s1">getValues</span><span class="s2">();</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">oldValue_one</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">newValue_one</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">cellsChanged</span><span class="s2"> = </span><span class="s8">0</span><span class="s2">;</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s4">for</span><span class="s1"> (</span><span class="s4">var</span><span class="s1"> </span><span class="s3">row</span><span class="s1">=</span><span class="s8">0</span><span class="s1">; </span><span class="s3">row</span><span class="s1">&lt;</span><span class="s3">data</span><span class="s1">.</span><span class="s3">length</span><span class="s1">; </span><span class="s3">row</span><span class="s1">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">      </span></span><span class="s4">for</span><span class="s2"> (</span><span class="s4">var</span><span class="s2"> </span><span class="s1">item</span><span class="s2">=</span><span class="s8">0</span><span class="s2">; </span><span class="s1">item</span><span class="s2">&lt;</span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">].</span><span class="s1">length</span><span class="s2">; </span><span class="s1">item</span><span class="s2">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">oldValue_one</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">];</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">newValue_one</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">].</span><span class="s1">replace</span><span class="s2">(</span><span class="s1">to_replace_one</span><span class="s2">, </span><span class="s1">replace_with_one</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">if</span><span class="s2"> (</span><span class="s1">oldValue_one</span><span class="s2">!=</span><span class="s1">newValue_one</span><span class="s2">)</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">          </span></span><span class="s3">cellsChanged</span><span class="s1">++;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">          </span></span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">] = </span><span class="s1">newValue_one</span><span class="s2">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">      </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>}</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">range</span><span class="s2">.</span><span class="s1">setValues</span><span class="s2">(</span><span class="s1">data</span><span class="s2">);</span></p>
<p class="p4"><span class="s1">}</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s4">function</span><span class="s2"> </span><span class="s1">replaceInSheetTwo</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">,</span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_two</span><span class="s2">, </span><span class="s1">replace_with_two</span><span class="s2">) {</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p5"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s3">ui</span><span class="s2"> = </span><span class="s1">SpreadsheetApp</span><span class="s2">.</span><span class="s3">getUi</span><span class="s2">();<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">spread</span><span class="s2"> = </span><span class="s5">SpreadsheetApp</span><span class="s2">.</span><span class="s1">getActiveSpreadsheet</span><span class="s2">();</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">data</span><span class="s2"><span class="Apple-converted-space">  </span>= </span><span class="s1">range</span><span class="s2">.</span><span class="s1">getValues</span><span class="s2">();</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">oldValue_two</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">newValue_two</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">cellsChanged</span><span class="s2"> = </span><span class="s8">0</span><span class="s2">;</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s4">for</span><span class="s1"> (</span><span class="s4">var</span><span class="s1"> </span><span class="s3">row</span><span class="s1">=</span><span class="s8">0</span><span class="s1">; </span><span class="s3">row</span><span class="s1">&lt;</span><span class="s3">data</span><span class="s1">.</span><span class="s3">length</span><span class="s1">; </span><span class="s3">row</span><span class="s1">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">      </span></span><span class="s4">for</span><span class="s2"> (</span><span class="s4">var</span><span class="s2"> </span><span class="s1">item</span><span class="s2">=</span><span class="s8">0</span><span class="s2">; </span><span class="s1">item</span><span class="s2">&lt;</span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">].</span><span class="s1">length</span><span class="s2">; </span><span class="s1">item</span><span class="s2">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">oldValue_two</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">];</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">newValue_two</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">].</span><span class="s1">replace</span><span class="s2">(</span><span class="s1">to_replace_two</span><span class="s2">, </span><span class="s1">replace_with_two</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">if</span><span class="s2"> (</span><span class="s1">oldValue_two</span><span class="s2">!=</span><span class="s1">newValue_two</span><span class="s2">)</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">          </span></span><span class="s3">cellsChanged</span><span class="s1">++;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">          </span></span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">] = </span><span class="s1">newValue_two</span><span class="s2">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">      </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>}</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">range</span><span class="s2">.</span><span class="s1">setValues</span><span class="s2">(</span><span class="s1">data</span><span class="s2">);</span></p>
<p class="p4"><span class="s1">}</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s4">function</span><span class="s2"> </span><span class="s1">replaceInSheetThree</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">,</span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_three</span><span class="s2">, </span><span class="s1">replace_with_three</span><span class="s2">) {</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p5"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s3">ui</span><span class="s2"> = </span><span class="s1">SpreadsheetApp</span><span class="s2">.</span><span class="s3">getUi</span><span class="s2">();<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">spread</span><span class="s2"> = </span><span class="s5">SpreadsheetApp</span><span class="s2">.</span><span class="s1">getActiveSpreadsheet</span><span class="s2">();</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">data</span><span class="s2"><span class="Apple-converted-space">  </span>= </span><span class="s1">range</span><span class="s2">.</span><span class="s1">getValues</span><span class="s2">();</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">oldValue_three</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">newValue_three</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">cellsChanged</span><span class="s2"> = </span><span class="s8">0</span><span class="s2">;</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s4">for</span><span class="s1"> (</span><span class="s4">var</span><span class="s1"> </span><span class="s3">row</span><span class="s1">=</span><span class="s8">0</span><span class="s1">; </span><span class="s3">row</span><span class="s1">&lt;</span><span class="s3">data</span><span class="s1">.</span><span class="s3">length</span><span class="s1">; </span><span class="s3">row</span><span class="s1">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">      </span></span><span class="s4">for</span><span class="s2"> (</span><span class="s4">var</span><span class="s2"> </span><span class="s1">item</span><span class="s2">=</span><span class="s8">0</span><span class="s2">; </span><span class="s1">item</span><span class="s2">&lt;</span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">].</span><span class="s1">length</span><span class="s2">; </span><span class="s1">item</span><span class="s2">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">oldValue_three</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">];</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">newValue_three</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">].</span><span class="s1">replace</span><span class="s2">(</span><span class="s1">to_replace_three</span><span class="s2">, </span><span class="s1">replace_with_three</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">if</span><span class="s2"> (</span><span class="s1">oldValue_three</span><span class="s2">!=</span><span class="s1">newValue_three</span><span class="s2">)</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">          </span></span><span class="s3">cellsChanged</span><span class="s1">++;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">          </span></span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">] = </span><span class="s1">newValue_three</span><span class="s2">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">      </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>}</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">range</span><span class="s2">.</span><span class="s1">setValues</span><span class="s2">(</span><span class="s1">data</span><span class="s2">);</span></p>
<p class="p4"><span class="s1">}</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s4">function</span><span class="s2"> </span><span class="s1">replaceInSheetFour</span><span class="s2">(</span><span class="s1">sheet</span><span class="s2">,</span><span class="s1">range</span><span class="s2">, </span><span class="s1">to_replace_four</span><span class="s2">, </span><span class="s1">replace_with_four</span><span class="s2">) {</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p5"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s3">ui</span><span class="s2"> = </span><span class="s1">SpreadsheetApp</span><span class="s2">.</span><span class="s3">getUi</span><span class="s2">();<span class="Apple-converted-space"> </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">spread</span><span class="s2"> = </span><span class="s5">SpreadsheetApp</span><span class="s2">.</span><span class="s1">getActiveSpreadsheet</span><span class="s2">();</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">data</span><span class="s2"><span class="Apple-converted-space">  </span>= </span><span class="s1">range</span><span class="s2">.</span><span class="s1">getValues</span><span class="s2">();</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">oldValue_four</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">newValue_four</span><span class="s2">=</span><span class="s6">""</span><span class="s2">;</span></p>
<p class="p3"><span class="s1"><span class="Apple-converted-space">  </span></span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">  </span></span><span class="s4">var</span><span class="s2"> </span><span class="s1">cellsChanged</span><span class="s2"> = </span><span class="s8">0</span><span class="s2">;</span></p>
<p class="p3"><span class="s7"></span><br></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span></span><span class="s4">for</span><span class="s1"> (</span><span class="s4">var</span><span class="s1"> </span><span class="s3">row</span><span class="s1">=</span><span class="s8">0</span><span class="s1">; </span><span class="s3">row</span><span class="s1">&lt;</span><span class="s3">data</span><span class="s1">.</span><span class="s3">length</span><span class="s1">; </span><span class="s3">row</span><span class="s1">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">      </span></span><span class="s4">for</span><span class="s2"> (</span><span class="s4">var</span><span class="s2"> </span><span class="s1">item</span><span class="s2">=</span><span class="s8">0</span><span class="s2">; </span><span class="s1">item</span><span class="s2">&lt;</span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">].</span><span class="s1">length</span><span class="s2">; </span><span class="s1">item</span><span class="s2">++) {</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">oldValue_four</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">];</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s1">newValue_four</span><span class="s2"> = </span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">].</span><span class="s1">replace</span><span class="s2">(</span><span class="s1">to_replace_four</span><span class="s2">, </span><span class="s1">replace_with_four</span><span class="s2">);</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">        </span></span><span class="s4">if</span><span class="s2"> (</span><span class="s1">oldValue_four</span><span class="s2">!=</span><span class="s1">newValue_four</span><span class="s2">)</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>{</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">          </span></span><span class="s3">cellsChanged</span><span class="s1">++;</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">          </span></span><span class="s1">data</span><span class="s2">[</span><span class="s1">row</span><span class="s2">][</span><span class="s1">item</span><span class="s2">] = </span><span class="s1">newValue_four</span><span class="s2">;</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">        </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">      </span>}</span></p>
<p class="p4"><span class="s1"><span class="Apple-converted-space">    </span>}</span></p>
<p class="p2"><span class="s2"><span class="Apple-converted-space">    </span></span><span class="s1">range</span><span class="s2">.</span><span class="s1">setValues</span><span class="s2">(</span><span class="s1">data</span><span class="s2">);</span></p>
<p class="p4"><span class="s1">}</span></p>
</body>
</html>
